/*
This JS is an example of what is generated by '/ads/index.php'. The 'abaabffcbeccac' element ID
below is an example of a random addlegate token. When modifying addlegate, be aware that some
browsers behave strangely and may truncate long HTML element IDs containing have numbers.
*/
window.onload = function() {document.getElementById("abaabffcbeccac").style = "display: none;"}
